[IV-24-25] Objetivo 0
Katakuri00/iv_budgettracker pull request #1
Opened 2024-10-02 11:07 UTC by Katakuri00

* [x ] ¿Se trata de un problema real del que se tenga conocimiento personal? **Sí**. Cuando en mi familia viajamos con nuestros tíos se da siempre esta situación.
* [x ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube? **Sí**. Para que cualquier miembro pueda hacer constatar los gastos o ingresos aportados desde su propio dispositivo.
* [x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando? **Sí**. La lógica matemática que respalda la gestión de los fondos.
* [x ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`? **Sí**. Mediante una lista de enlaces a las capturas de pantallas que muestran los resultados de la configuración.
* [x ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca? El usuario deberá introducir los **gastos e ingresos** generados en el fondo.
* [x ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo? **Sí**. Se ha seguido la lista de comprobación teniendo en cuenta lo incluido en el repositorio.

2024-10-02 13:24 UTC, JJ requested changes
Como no has puesto lo correspondiente al objetivo en el PR, no puedo comentar en cada línea específica. 
Dado que lo has extraido de un repositorio, ¿por qué has contestado positivamente a la pregunta?

> [x ] ¿Se trata de un problema real del que se tenga conocimiento personal? Sí. Cuando en mi familia viajamos con nuestros tíos se da siempre esta situación.

Lo que se propone en esta asignatura es que sigáis una metodología para resolver problemas. En concreto, en este objetivo es design thinking, a través del juego o por tu cuenta. Difícilmente "buscar en un repositorio" forma parte de una buena práctica pra resolver problemas. Y aunque en este caso pueda parecer que no es tan necesaria la metodología, el *hecho* de que comprendas la existencia de metodologías y comiences a aplicarlas sí es importante, y es mejor introducirlo en una tan simple como design thinking.

Por otro lado, también has respondido positivamente a

> [x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando? Sí. La lógica matemática que respalda la gestión de los fondos.

Aparte de sumar y restar, ¿qué lógica de negocio compleja hace falta? ¿Al menos en dos partes sólo?

2024-10-02 13:24 UTC, JJ commented on .gitignore
> -
¿Este cambio qué tiene que ver con el objetivo?

2024-10-02 13:24 UTC, JJ commented on README.md
>  Esta idea ha sido extraida del conjunto de proyectos a resolver listados en [este repositorio](https://github.com/karan/Projects-Solutions/blob/master/README.md).
La idea debe estar en el PR, para que se pueda comentar.

2024-10-03 09:20 UTC, Katakuri00 commented on README.md
>  Esta idea ha sido extraida del conjunto de proyectos a resolver listados en [este repositorio](https://github.com/karan/Projects-Solutions/blob/master/README.md).
Entiendo, lo tendré en cuenta en la próxima versión.

2024-10-03 09:47 UTC, Katakuri00 commented
> Como no has puesto lo correspondiente al objetivo en el PR, no puedo comentar en cada línea específica. Dado que lo has extraido de un repositorio, ¿por qué has contestado positivamente a la pregunta?

Lo he expresado mal. El enunciado que vi en el repositorio fue lo que me inspiró a encontrar el problema, pensaba que era apropiado anotarlo. Aun con eso en cuenta, veo que el objetivo en sí no es encontrar un proyecto a desarrollar, sino encontrar un problema a resolver.

> Lo que se propone en esta asignatura es que sigáis una metodología para resolver problemas. En concreto, en este objetivo es design thinking, a través del juego o por tu cuenta. Difícilmente "buscar en un repositorio" forma parte de una buena práctica pra resolver problemas. Y aunque en este caso pueda parecer que no es tan necesaria la metodología, el _hecho_ de que comprendas la existencia de metodologías y comiences a aplicarlas sí es importante, y es mejor introducirlo en una tan simple como design thinking.

Con esto me queda claro. Pensaré en un otro problema si es necesario.

> Aparte de sumar y restar, ¿qué lógica de negocio compleja hace falta? ¿Al menos en dos partes sólo?

No entiendo a qué se refiere con dos partes, pero se trata de un supuesto simple. Reflexionaré sobre ello.

2024-10-03 09:55 UTC, JJ commented
> > Aparte de sumar y restar, ¿qué lógica de negocio compleja hace falta? ¿Al menos en dos partes sólo?
> 
> No entiendo a qué se refiere con dos partes, pero se trata de un supuesto simple. Reflexionaré sobre ello.

Como dice [el guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio):

> En general, este tipo de problemas requieren, por parte de la solución informática, una parte considerable de “computación” o “procesamiento” o “generación”.

Se trata de que se idee una solución al problema que requiera cierta descomposición del mismo y testeo por partes, lo que se hará en el 4º objetivo. Una suma y división no hace falta que se testee, va a funcionar, escribir tests para los mismos no requiere ningún esfuerzo.

En todo caso, el problema también es que realmente *no* hay un problema, al menos con dos partes solo. En este objetivo hay que usar *design thinking* para encontrar un problema, como te he comentado. El hecho de que eventualmente hayas enviado algo tan simple que se resuelve con sumas y divisiones viene de que no has seguido ese proceso, sino buscado en una página. Los problemas reales no son tan sencillos de resolver, ni siquiera una parte mínima del problema que se pueda abordar en esta asignatura.

2024-10-04 09:40 UTC, Katakuri00 commented
He actualizado el README con un nuevo problema tratando de seguir la metodología de _design thinking_. He observado las referencias del guión sobre distintos conjuntos de datos y al centrarme en la parte de economía me ha surgido esta idea apoyándome [en esta noticia](https://www.antena3.com/noticias/economia/economia-espanola-crece-pero-precio-alimentos-vivienda-desajustan-cuentas-dia-dia_2024091966ec262cb3741e0001ebc64c.html) de actualidad. También he modificado las explicaciones asociadas a la lista de comprobación en los puntos necesarios, en especial la parte de lógica de negocio. Espero su revisión.

2024-10-07 05:39 UTC, JJ requested changes
En general, sería extremadamente conveniente primero que realmente aplicárais la metodología de *design thinking*, que te ayuda a entender un problema y por supuesto a describirlo (en esta asignatura, a un posible cliente, lo que sea). Pero desde un punto de vista simplemente pragmático, sería muy conveniente que pensárais que esto es una descripción de un problema con el que vais a trabajar, vosotros y posiblemente otra persona, durante el resto de la asignatura, la base para el desarrollo de una aplicación. ¿Crees que con lo que has incluido se delimita siquiera por dónde se podría empezar a trabajar en una aplicación?

2024-10-07 05:39 UTC, JJ commented on .gitignore
> -
Entonces no lo incluyas en el PR. Lo puedes sacar del PR haciendo un rebase, y te rogaría que lo hicieras.

2024-10-07 05:39 UTC, JJ commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
De forma precisa, ¿cuál es el problema? 
En todo caso, resolver el problema implicaría que se compran alimentos más saludables, por lo que entiendo. ¿El programa va a comprobar qué alimentos se compran y que efectivamente mejoran la salud?
La formulación del problema no está clara, pero por lo que parece entender, quizás debas de [volver a leer el guión](https://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) donde dice:

> ¿Qué tipo de problemas no van a ser adecuados?

> Todos los problemas que requieran entradas físicas; todos aquellos en los que el usuario o cliente tenga que introducir mucha información. En general, todo problema que no se entienda bien.

Tampoco entiendo muy bien qué tiene que ver la comida saludable con la edad de emancipación.

2024-10-07 10:50 UTC, Katakuri00 commented
> Entonces no lo incluyas en el PR. Lo puedes sacar del PR haciendo un rebase, y te rogaría que lo hicieras.
Rebase realizado :+1:
> ¿Crees que con lo que has incluido se delimita siquiera por dónde se podría empezar a trabajar en una aplicación?
No lo había pensado así. Voy a darle otra vuelta para capturar esas ideas.

2024-10-07 10:51 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
> Entonces no lo incluyas en el PR. Lo puedes sacar del PR haciendo un rebase, y te rogaría que lo hicieras.

Rebase realizado 👍 .

> ¿Crees que con lo que has incluido se delimita siquiera por dónde se podría empezar a trabajar en una aplicación?

No lo había pensado así. Voy a darle otra vuelta para capturar esas ideas.

2024-10-07 10:52 UTC, Katakuri00 commented
> Entonces no lo incluyas en el PR. Lo puedes sacar del PR haciendo un rebase, y te rogaría que lo hicieras.

Rebase realizado 👍 .

> ¿Crees que con lo que has incluido se delimita siquiera por dónde se podría empezar a trabajar en una aplicación?

No lo había pensado así. Voy a darle otra vuelta para capturar esas ideas.

2024-10-07 11:15 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
> De forma precisa, ¿cuál es el problema?

El objetivo es simplificar la tarea al realizar la cesta de la compra. Es habitual acudir a diferentes supermercados en busca de la opción más asequible o la que más se adapta a los gustos de cada persona. Mi idea es que el cliente puede elaborar su lista en base a sus preferencias, y que el resultado sea una lista de productos concretos. En definitiva, que el cliente no necesite ir a cada establecimiento, o compara precios en la web, sino que la aplicación lo resuelva de forma óptima.

> Tampoco entiendo muy bien qué tiene que ver la comida saludable con la edad de emancipación.

No pretendo relacionar estas ideas. Con el dato de la emancipación, trato de aportar que el problema afecta también a los jovenes, del mismo modo que, por otra parte, productos como la fruta [han visto disminuido su consumo](https://www.lasexta.com/noticias/sociedad/espanoles-comemos-menos-fruta-que-hace-diez-anos-precio-calidad-productos-principales-factores-caida_2024070166830b21ab9b4800014532de.html) debido al aumento de su precio, siendo la fruta un producto esencial para llevar una dieta saludable.

Si esos comentarios a la hora de describir el problema enturbian la idea esencial del problema en sí, los puedo eliminar de la descripción.

2024-10-09 08:54 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
> Si lo que te preocupa es el precio de la fruta, hay muchos problemas de extracción de información de entornos poco estructurados que podrías abordar. ¿Es eso lo que te interesa? (Y de camino comprobar que, pese a lo que se haya podido escuchar, el precio de la fruta sube en origen y en donde se comercializa)

Se podría llevar a cabo un análisis del precio de la fruta para recomendar a un cliente la compra de una u otra en función de los datos de producción y transporte. ¿Sería posible? Tendría que estudiar un poco el tema, pero suena interesante el analizar los datos actuales necesarios para estimar el precio de la fruta en los próximos días, por ejemplo.

2024-10-09 09:02 UTC, JJ commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
¿Tienes esos datos? ¿Tienes un buen algoritmo de estimación? ¿Qué error en la estimación sería aceptable para el cliente? Y una vez que hagas una recomendación, ¿vas a preguntarle al cliente si le ha resuelto el problema o simplemente darás por bueno lo que sea que diga el algoritmo?
Dicho de otro modo, no sé por qué insistís en complicar problemas cuando un problema de extracción de información sería perfectamente válido.

2024-10-09 10:38 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
Es cierto, sería complicarse demasiado. He encontrado información sobre patrones de consumo de diferentes alimentos según diferentes grupos de población. Los hay por edad, nacionalidad, comunidad autónoma, entre otros. He pensado en usar esa información para recomendar la compra de alimentos en función de estos patrones. Por poner un ejemplo, si un señor andaluz de 50 años, en general, tiene déficit de consumo de frutas, se le podría recomendar su compra. El único problema que le veo a esta solución es que no veo la necesidad de hacer un despliegue en la nube. ¿Cómo podría hacerlo?

2024-10-09 15:41 UTC, JJ commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
Sin poder comrpobar si una persona se come o no la fruta que le dices, ¿crees que el problema es desplegar en la nube?

2024-10-09 16:54 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
Entiendo que se refiere a que la información que se extrae debe tener utilidad para el cliente y que, al no saber si se compra el alimento, no se cumple eso. En cualquier caso estoy bastante bloqueado con este tema, aunque intentaré pensar en otra solución.

Por otra parte, creo que he dado con otro problema que podría ser interesante. Últimamente, un grupo de amigos y yo hemos estado quedando para hacer deporte al aire libre y, en la última ocasión, casi acabamos sofocados por el calor que hacía en ese momento del día. La idea sería utilizar los datos climatológicos del día para concertar un evento deportivo al que puedan apuntarse las personas que quieran participar. El evento podría configurarse para establecer la hora y el lugar, en función de cada participante, por lo que tendría sentido hacerlo en la nube.

2024-10-09 16:58 UTC, JJ commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
Precisamente para no bloquearse están las metodologías. En este objetivo aconsejamos que se use *design thinking*. Puedes hacerlo a través del juego de rol que se recomienda en el guión, o por tu cuenta. Las metodologías aseguran que a partir de identificar una persona con un problema, se pueda llegar a una descripción con la que trabajar.
Mira también en [el guión](https://jj.github.io/IV/documentos/proyecto/0.Repositorio#explicaci%C3%B3n) posibles fuentes de datos que, en caso de estar poco estructuradas, pueden ser un problema interesante que abordar. ¿Habrá alguna fuente de datos poco estructurada con los precios de la fruta? ¿Por ejemplo, las lonjas de frutas? ¿O el Mercagranada?

2024-10-09 17:59 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
> Precisamente para no bloquearse están las metodologías. En este objetivo aconsejamos que se use _design thinking_. Puedes hacerlo a través del juego de rol que se recomienda en el guión, o por tu cuenta. Las metodologías aseguran que a partir de identificar una persona con un problema, se pueda llegar a una descripción con la que trabajar.

El enlace al juego de rol que aparece en el guión es incorrecto (error 404). Hasta ahora he estado aplicando los puntos que se recomiendan en el guión e investigando las fuentes de datos que se aportan en el mismo. También he consultado el material adicional sobre _design thinking_ y _lógica de negocio_.

> ¿Habrá alguna fuente de datos poco estructurada con los precios de la fruta? ¿Por ejemplo, las lonjas de frutas? ¿O el Mercagranada?

Sería interesante trabajar con esos datos, pero no encuentro qué información se puede extraer que sea de utilidad para un cliente siguiendo los requisitos que se apuntan en el guión, y que resuelvan las preguntas que han surgido en este hilo.

¿Puede comentarme también que opina sobre la otra idea que he descrito?

2024-10-09 18:06 UTC, JJ commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
Está enlazado desde la sesión de la semana http://jj.github.io/IV/documentos/actividades/juego-rol-design-thinking
Para solicitar revisión a partir de ahora pon simplemente un comentario con @JJ solicitando revisión. No he visto que hayas hecho nada nuevo desde hace dos días.

2024-10-16 15:28 UTC, Katakuri00 commented on README.md
> +En los últimos años, el crecimiento del precio de la vivienda y la cesta de la compra han desajustado las cuentas de muchos hogares españoles donde los sueldos no alcanzan a cubrir estos gastos, espe
@JJ, solicito revisión por favor.

2024-10-16 16:14 UTC, JJ requested changes
Si *realmente* se trata de un problema con el que estás familiarizado y *realmente* no almacenan los presupuestos en un formato estructurado (no generado por una hoja de cálculo, por ejemplo), y *realmente* extraer esos datos resuelve algún problema, se podría usar. Pero tendrías que incluir un ejemplo de esos documentos para ver que realmente es así.

2024-10-16 16:14 UTC, JJ commented on README.md
> +Una empresa de construcción y mantenimiento busca organizar los datos del historial de presupuestos de la empresa almacenados en una serie de documentos de texto para extraer la información sobre el
1. ¿Tienes una empresa de construcción?
2. ¿Por qué busca eso? De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md)

> Si se describe lo que el cliente quiere hacer sin decir por qué quiere hacerlo, no estás describiendo el problema, estás describiendo una solución.

3. En caso que haya duda, la descripción del problema tiene que incluir la descripción de la lógica de negocio. Y esta (tomado del fichero de errores frecuentes):

> No incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “avisar”, “enviar”, “recuperar”, “integrar”, “alertar”, “comunicar”.

2024-10-16 16:14 UTC, JJ commented on README.md
> +Se trata de un problema de extracción de información de una fuente de datos no estructurada en la que el cliente busca dar valor a los datos almacenados para mejorar la gestión y organización de la e
¿Una empresa de construcción tiene los presupuestos en un formato no estructurado?

2024-10-16 17:00 UTC, Katakuri00 commented on README.md
> +Se trata de un problema de extracción de información de una fuente de datos no estructurada en la que el cliente busca dar valor a los datos almacenados para mejorar la gestión y organización de la e
En este caso, al menos, cada presupuesto se presenta en forma de documento de texto a un cliente con una descripción del plan de obra y los costes. No tienen más utilidad que esa.

2024-10-16 17:15 UTC, JJ commented on README.md
> +Se trata de un problema de extracción de información de una fuente de datos no estructurada en la que el cliente busca dar valor a los datos almacenados para mejorar la gestión y organización de la e
¿Documento generado a partir de qué?
¿Por qué querría una empresa extraer información de esos documentos? ¿No será más fácil introducirlo donde sea necesario y que genere el presupuesto a partir de ahí? ¿Y luego si necesita info que la extraiga del mismo sistema?
Si se usa *design thinking*, se identifican los verdaderos problemas, no se buscan problemas artificiales para poder pasar el objetivo. En este objetivo precisamente se trata de aprender a usar esta metodología. En otros objetivos se usarán otras metodologías, y también habrá que usarlas.

2024-10-16 17:29 UTC, Katakuri00 commented on README.md
> +Una empresa de construcción y mantenimiento busca organizar los datos del historial de presupuestos de la empresa almacenados en una serie de documentos de texto para extraer la información sobre el
> 1. ¿Tienes una empresa de construcción?

Mi padre la tiene, una PYME.

> 2. ¿Por qué busca eso? De [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md)

Tiene registros de presupuestos desde el año 2012 hasta hoy y beneficiaría en varios puntos la gestión de las obras. En primer lugar en la agilidad a la hora de adquirir la información relativa a los proyectos en curso, además la elaboración de nuevos proyectos podrían contrastarse con presupuestos anteriores para determinar las inversiones de materiales, lo que ayudaría a reducir costes en almacenamiento y adquisición del utillaje. Se me ha olvidado comentar que, junto a los presupuestos, también se incluye en los datos un conjunto de facturas que se presentan a la gestoría para realizar el balance económico de la empresa.

> 3. En caso que haya duda, la descripción del problema tiene que incluir la descripción de la lógica de negocio. Y esta (tomado del fichero de errores frecuentes):

Resumiendo. La empresa genera unos presupuestos que sirven como estimaciones de los costes del proyecto de obra, presentándose al cliente (de la empresa) para su aprobación. Cuando la obra ha finalizado y el cobro se ha realizado, se genera una factura. Todos esos datos están registrados en documentos de texto y no tienen ningún valor útil para la empresa. Nuestro cliente quiere organizar esa información para optimizar el rendimiento de la empresa.

Voy a reescribir descripción para dejar todo esto claro en el README.

2024-10-16 18:04 UTC, JJ requested changes
En caso de que vayas a optar por el documento HTML o texto, por favor, elimina el docx de aquí y sustitúyelo por el que vayas a usar.

2024-10-16 18:04 UTC, JJ commented on Docs/presupuesto.docx
OK, ya veo. El problema ahora es que, como te he dicho arriba, tienes que escribir tú todo el código que vayas a usar en la asignatura. No puedes usar un lector de .docx, ni un lector de ficheros zip (que es lo que es un docx) con XML dentro (que es donde se almacena la información).
Si quieres ir por ahí, tendrás que escribir bibliotecas que hagan esto, y hacerlo desde cero dentro de lo posible, con un PMV que se adapte al problema específico (por ejemplo, que no extraiga todos los ficheros, sino uno solo)
Como alternativa puede ser exportar todos esos archivos a texto plano o HTML y trabajar con el HTML. También tendrás que procesarlo a mano, pero es más fácil de procesar.

2024-10-16 18:12 UTC, Katakuri00 commented on README.md
> +Se trata de un problema de extracción de información de una fuente de datos no estructurada en la que el cliente busca dar valor a los datos almacenados para mejorar la gestión y organización de la e
> ¿Documento generado a partir de qué? 

Son documentos escritos a mano.

> ¿Por qué querría una empresa extraer información de esos documentos? 

Para aprender de la propia experiencia de la empresa y para agilizar la generación de nuevos presupuestos.

> ¿No será más fácil introducirlo donde sea necesario y que genere el presupuesto a partir de ahí? ¿Y luego si necesita info que la extraiga del mismo sistema? 

Pues imagino que se podrá. Pero estamos hablando de una pequeña empresa de un pueblo en la que el método de trabajo consiste en: Contactar con un cliente, concretar los planes de obra, escribir las ideas acordadas en un documento con la estimación del coste total, y si el cliente acepta, se inicia la obra. 

> Si se usa _design thinking_, se identifican los verdaderos problemas, no se buscan problemas artificiales para poder pasar el objetivo. En este objetivo precisamente se trata de aprender a usar esta metodología. En otros objetivos se usarán otras metodologías, y también habrá que usarlas.

Literalmente esta idea surgió de una conversación _real_ con el cliente. Tras haber buscado información sobre la gestión de datos no estructurados e intentarlo con el mercado de la fruta con las opciones que me proporcionó, sin éxito, pensé que en este caso se me había presentado una proyecto interesante.

2024-10-16 18:18 UTC, JJ commented on README.md
> +Se trata de un problema de extracción de información de una fuente de datos no estructurada en la que el cliente busca dar valor a los datos almacenados para mejorar la gestión y organización de la e
Me parece genial. Ya habías respondido a esto de todas formas con la subida del fichero. Te agradezco de todas formas la aclaración.

2024-10-16 18:24 UTC, Katakuri00 commented on Docs/presupuesto.docx
Hecho 👍 . Lo he exportado a texto plano y lo he actualizado.

2024-10-16 18:38 UTC, JJ approved these changes
:+1: 
Cuando vengas te explico el 1 o comienza cuando quieras.

2024-10-17 10:22 UTC, merged